
import {
   addLeadingLocalDash,
   cleanPath,
   getJsonParts,
   isAbsolutePath,
   isSubPath,
   joinPaths,
   pathAsUnix,
   getRelativePath,
   getSubrelativePathFromAbsoluteRootPath,
   getAbsolutePathFromRelatrivePath,
   sharedPath,
   sleep,
   splitPath,
   subtractPath,
   toKebabCase,
   toCamelCase,
   toPascalCase,
   toSnakeCase,
   trimDashes,
   trimLeadingDash,
   getErrorInfo,
   getTimestamp,
   getJSONCircularReplacer,
   toJSONString,
   maxDepthReplacer,
   keyValueReplacer,
   objectWalker,
   ObjectWalkerCallback,
} from './vsc-base-raw'

import {
   ask,
   pick,
   findFilePaths,
   findFilePathsFromBase,
   findRelativeFilePaths,
   getActiveEditor,
   getActiveDocument,
   createVscodeRangeAndPosition,
   VscodePosition,
   createSelection,
   setSelection,
   setSelections,
   addSelection,
   setSelectionFromRange,
   setSelectionsFromRanges,
   addSelectionFromRange,
   newDocument,
   getActiveTerminal,
   writeToTerminal,
   getDocumentPath,
   getDocumentContent,
   setDocumentContent,
   getFullDocumentRange,
   appendToDocument,
   appendLineToDocument,
   prependToDocument,
   prependLineToDocument,
   saveDocument,
   getRootPath,
   saveAll,
   showErrorMessage,
   showMessage,
} from './vsc-base-vscode';


import {
   getLineStreamReader,
   getReadStream,
   doesExists,
   getDir,
   getFileContent,
   getJsonContent,
   getConfig,
   getPackageFilePaths,
   getPackageDependencies,
   isDir,
   makeDir,
   move,
   copy,
   addFileContent,
   emptyDir,
   remove,
   saveFileContent,
   execFromPath,
} from './vsc-base-system';

import {
   getVscDefaultModuleMap,
   varifyModuleMethods,
   awaitResult,
   tsTranspile,
   tsLoadModuleSourceCode,
   tsRewriteTranpiledCodeWithVscBaseModules,
   tsLoadModule,
   TSLoadModuleError,
   tsCreateTransformer,
   tsCreateRemoveNodesTransformer,
   tsCreateNodeVisitor,
   tsTransform,
   tsVisitWithTransformers,
   tsTransformNode,
   TsDefaultCompilerOptions,
   tsCreateSourceFile,
   tsGetParsedChildren,
   tsFindNodePositionFromContent,
   tsFindAllNodePositionsFromContent,
   tsReplace,
   tsReplaceAll,
   tsFindChild,
   tsFindGrandChild,
   tsFindAncestor,

   tsHasChild,
   tsHasChildren,
   tsHasGrandChild,
   tsHasGrandChildren,
   tsHasAncestor,
   tsHasAncestors,

   tsMatchObjectProperty,
   tsMatchInterface,
   tsMatchTypeRef,
   tsMatchEnum,
   tsMatchEnumMember,
   tsMatchFunction,
   tsMatchVariable,
   tsMatchIdentifier,

   tsIsObjectProperty,
   tsIsInterface,
   tsIsTypeRef,
   tsIsEnum,
   tsIsEnumMember,
   tsIsFunction,
   tsIsVariable,
   tsIsIdentifier,

   tsIsValue,
   tsIsNode
} from './vsc-base-typescript';

import {
   scaffoldTemplate,
   vscTemplate,
   vscTemplateItem,
   vscTemplateFolder,
   vscTemplateFile,
   vscUserInput,
   vscUserInputs,
   vscStringDelegate,
} from './vsc-base-vscTemplate';


export {
   vscTemplate,
   vscTemplateItem,
   vscTemplateFolder,
   vscTemplateFile,
   vscUserInput,
   vscUserInputs,
   vscStringDelegate,
}

export {
   //raw
   addLeadingLocalDash,
   cleanPath,
   getJsonParts,
   isAbsolutePath,
   isSubPath,
   joinPaths,
   pathAsUnix,
   getAbsolutePathFromRelatrivePath,
   getRelativePath,
   getSubrelativePathFromAbsoluteRootPath,
   sharedPath,
   sleep,
   splitPath,
   subtractPath,
   toKebabCase,
   toCamelCase,
   toPascalCase,
   toSnakeCase,
   trimDashes,
   trimLeadingDash,
   getErrorInfo,
   getTimestamp,
   getJSONCircularReplacer,
   toJSONString,
   maxDepthReplacer,
   keyValueReplacer,
   objectWalker,
   ObjectWalkerCallback,
}
export {
   //vscode
   ask,
   pick,
   findFilePaths,
   findFilePathsFromBase,
   findRelativeFilePaths,
   getActiveEditor,
   getActiveDocument,
   newDocument,
   createVscodeRangeAndPosition,
   VscodePosition,
   createSelection,
   setSelection,
   setSelections,
   addSelection,
   setSelectionFromRange,
   setSelectionsFromRanges,
   addSelectionFromRange,
   getActiveTerminal,
   writeToTerminal,
   getDocumentPath,
   getDocumentContent,
   setDocumentContent,
   getFullDocumentRange,
   appendToDocument,
   appendLineToDocument,
   prependToDocument,
   prependLineToDocument,
   saveDocument,
   getRootPath,
   saveAll,
   showErrorMessage,
   showMessage,
}
export {
   //system
   getLineStreamReader,
   getReadStream,
   doesExists,
   getDir,
   getFileContent,
   getJsonContent,
   getConfig,
   getPackageFilePaths,
   getPackageDependencies,
   isDir,
   makeDir,
   move,
   copy,
   addFileContent,
   emptyDir,
   remove,
   saveFileContent,
   scaffoldTemplate,
   execFromPath,
}
export {
   // ts
   getVscDefaultModuleMap,
   awaitResult,
   varifyModuleMethods,
   tsTranspile,
   tsLoadModuleSourceCode,
   tsRewriteTranpiledCodeWithVscBaseModules,
   tsLoadModule,
   TSLoadModuleError,
   tsCreateSourceFile,
   TsDefaultCompilerOptions,
   //
   tsCreateTransformer,
   tsCreateRemoveNodesTransformer,
   tsCreateNodeVisitor,
   tsTransform,
   tsVisitWithTransformers,
   tsTransformNode,
   //
   tsFindNodePositionFromContent,
   tsFindAllNodePositionsFromContent,
   tsReplace,
   tsReplaceAll,
   tsGetParsedChildren,
   //
   tsFindChild,
   tsFindGrandChild,
   tsFindAncestor,
   tsHasChild,
   tsHasChildren,
   tsHasGrandChild,
   tsHasGrandChildren,
   tsHasAncestor,
   tsHasAncestors,
   //node test
   tsMatchTypeRef,
   tsMatchInterface,
   tsMatchEnum,
   tsMatchEnumMember,
   tsMatchObjectProperty,
   tsMatchFunction,
   tsMatchVariable,
   tsMatchIdentifier,
   //boolean tests
   tsIsObjectProperty,
   tsIsInterface,
   tsIsTypeRef,
   tsIsEnum,
   tsIsEnumMember,
   tsIsFunction,
   tsIsVariable,
   tsIsIdentifier,
   tsIsValue,
   tsIsNode
}
