
import {
   addLeadingLocalDash,
   cleanPath,
   getJsonParts,
   isAbsolutePath,
   isSubPath,
   joinPaths,
   pathAsUnix,
   getRelativePath,
   getSubrelativePathFromAbsoluteRootPath,
   getAbsolutePathFromRelatrivePath,
   sharedPath,
   sleep,
   splitPath,
   subtractPath,
   toKebabCase,
   toCamelCase,
   toPascalCase,
   toSnakeCase,
   trimDashes,
   trimLeadingDash,
   getErrorInfo,
   getTimestamp,
   getJSONCircularReplacer,
   toJSONString,
   maxDepthReplacer,
   keyValueReplacer,
   objectWalker,
   ObjectWalkerCallback
} from './vsc-base-raw'

import {
   ask,
   pick,
   findFilePaths,
   findFilePathsFromBase,
   findRelativeFilePaths,
   getActiveEditor,
   getActiveDocument,
   getComplexRangeObject,
   createSelection,
   setSelection,
   addSelection,
   setSelectionFromRange,
   addSelectionFromRange,
   newDocument,
   getActiveTerminal,
   writeToTerminal,
   getDocumentPath,
   getDocumentContent,
   setDocumentContent,
   getFullDocumentRange,
   appendToDocument,
   appendLineToDocument,
   prependToDocument,
   prependLineToDocument,
   saveDocument,
   getRootPath,
   saveAll,
   showErrorMessage,
   showMessage
} from './vsc-base-vscode';


import {
   getLineStreamReader,
   getReadStream,
   doesExists,
   getDir,
   getFileContent,
   getJsonContent,
   getConfig,
   getPackageFilePaths,
   getPackageDependencies,
   isDir,
   makeDir,
   move,
   copy,
   saveFileContent,
   execFromPath
} from './vsc-base-system';

import {
   getVscDefaultModuleMap,
   varifyModuleMethods,
   awaitResult,
   tsTranspile,
   tsLoadModuleSourceCode,
   tsRewriteTranpiledCodeWithVscBaseModules,
   tsLoadModule,
   TSLoadModuleError,
   tsCreateTransformer,
   TsTransformerCallback,
   tsCreateRemoveNodesTransformer,
   TsRemoveTransformerCallback,
   tsCreateNodeVisitor,
   TsNodeVisitorCallback,
   tsTransform,
   tsTransformNode,
   TsDefaultCompilerOptions,
   tsCreateSourceFile,
   tsGetParsedChildren
} from './vsc-base-typescript';

import {
   scaffoldTemplate,
   vscTemplate,
   vscTemplateItem,
   vscTemplateFolder,
   vscTemplateFile,
   vscUserInput,
   vscUserInputs,
   vscStringDelegate
} from './vsc-base-vscTemplate';


export {
   vscTemplate,
   vscTemplateItem,
   vscTemplateFolder,
   vscTemplateFile,
   vscUserInput,
   vscUserInputs,
   vscStringDelegate
}

export {
   //raw
   addLeadingLocalDash,
   cleanPath,
   getJsonParts,
   isAbsolutePath,
   isSubPath,
   joinPaths,
   pathAsUnix,
   getAbsolutePathFromRelatrivePath,
   getRelativePath,
   getSubrelativePathFromAbsoluteRootPath,
   sharedPath,
   sleep,
   splitPath,
   subtractPath,
   toKebabCase,
   toCamelCase,
   toPascalCase,
   toSnakeCase,
   trimDashes,
   trimLeadingDash,
   getErrorInfo,
   getTimestamp,
   getJSONCircularReplacer,
   toJSONString,
   maxDepthReplacer,
   keyValueReplacer,
   objectWalker,
   ObjectWalkerCallback,
}
export {
   //vscode
   ask,
   pick,
   findFilePaths,
   findFilePathsFromBase,
   findRelativeFilePaths,
   getActiveEditor,
   getActiveDocument,
   newDocument,
   getComplexRangeObject,
   createSelection,
   setSelection,
   addSelection,
   setSelectionFromRange,
   addSelectionFromRange,
   getActiveTerminal,
   writeToTerminal,
   getDocumentPath,
   getDocumentContent,
   setDocumentContent,
   getFullDocumentRange,
   appendToDocument,
   appendLineToDocument,
   prependToDocument,
   prependLineToDocument,
   saveDocument,
   getRootPath,
   saveAll,
   showErrorMessage,
   showMessage,
}
export {
   //system
   getLineStreamReader,
   getReadStream,
   doesExists,
   getDir,
   getFileContent,
   getJsonContent,
   getConfig,
   getPackageFilePaths,
   getPackageDependencies,
   isDir,
   makeDir,
   move,
   copy,
   saveFileContent,
   scaffoldTemplate,
   execFromPath
}
export {
   // ts
   getVscDefaultModuleMap,
   awaitResult,
   varifyModuleMethods,
   tsTranspile,
   tsLoadModuleSourceCode,
   tsRewriteTranpiledCodeWithVscBaseModules,
   tsLoadModule,
   TSLoadModuleError,
   tsCreateTransformer,
   TsTransformerCallback,
   tsCreateRemoveNodesTransformer,
   TsRemoveTransformerCallback,
   tsCreateNodeVisitor,
   TsNodeVisitorCallback,
   tsTransform,
   tsTransformNode,
   TsDefaultCompilerOptions,
   tsCreateSourceFile,
   tsGetParsedChildren
   // template types
}
